// newwebui/src/web-components/data-table.ts
import { LitElement, html, css } from 'lit';
import { customElement, property  } from 'lit/decorators.js';
import '@swimlane/ngx-datatable';

@customElement('data-table')
export class DataTable extends LitElement{
  
  static styles = css`
  @media screen and (max-width: 800px) {
    .desktop-hidden {
      display: initial;
    }
    .mobile-hidden {
      display: none;
    }
  }
  @media screen and (min-width: 800px) {
    .desktop-hidden {
      display: none;
    }
    .mobile-hidden {
      display: initial;
    }
  }
  .input-search{
    width:100%;
    align-self: right;
    border-radius: 5px;
    width: 20%;
  }  
  `;
  @property({ type: Array }) 
  ids: Array<any>;
  @property({ type: Array }) 
  rows: Array<any>;
  @property({ type: Array }) 
  columns: Array<any>;

  render() {

    return html`
    
    <div>
      <div style="text-align: end;">
        <ion-item class="input-search">
          <ion-label position="stacked">Search:</ion-label>
          <ion-input placeholder="Type to filter the name column..." (keyup)="updateFilter($event)" ></ion-input>
        </ion-item>
      </div>
       <div style="float:left;width:95%">

       <ngx-datatable
          style="width: 95%"
          class="bootstrap"
          [rows]="rows"
          [columnMode]="ColumnMode.force"
          [headerHeight]="'auto'"
          [footerHeight]="'auto'"
          [rowHeight]="'auto'"
          [limit]="5"
          [selected]="selected"
          [selectionType]="SelectionType.checkbox"
          [selectAllRowsOnPage]="false"
          [displayCheck]="displayCheck"
            [scrollbarH]="true"
          (activate)="onActivate($event)"
          (select)="onSelect($event)"
        >
          <ngx-datatable-column
          style="margin: 5px;"
            [width]="30"
            [sortable]="false"
            [canAutoResize]="false"
            [draggable]="true"
            [resizeable]="false"
            [headerCheckboxable]="true"
            [checkboxable]="true"
          >
          ${this.print()}
          </ngx-datatable-column>
          ${this.columns.map(column=> html`
          <ngx-datatable-column name="{{${column.name}}}" >${column.name}</ngx-datatable-column>`)}

        
        </ngx-datatable>
         
          
      </div> 
    </div> `;
  }
  print(){
  }

}

// newwebui/src/app/components/data-table/data-table.component.ts
// @ts-check
import {
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  SimpleChanges,
  ViewChild,
} from '@angular/core'
import { Router } from '@angular/router'
import { TranslateService } from '@ngx-translate/core'
import { ColumnMode, SelectionType } from '@swimlane/ngx-datatable'
import { EngineService } from 'src/app/services/engine.service'
/**
 * @ignore
 */
@Component({
  selector: 'app-data-table',
  templateUrl: './data-table.component.html',
  styleUrls: ['./data-table.component.scss'],
})
export class DataTableComponent implements OnInit {
  /**
   * Name Columnc
   * @param {Object}
   */
  @Input() columns: any
  /**
   * If is proposal
   * @param {Boolean}
   */
  @Input() isProp: boolean
  /**
   * if is inspection
   * @param {Boolean}
   */
  @Input() isInsp: boolean
  /**
   * if is work order
   * @param {Boolean}
   */
  @Input() haveCont: boolean
  /**
   * Rows data
   * @param {Object}
   */
  @Input() listRows: any
  /**
   * Data selected
   * @param {Array}
   */
  @Output() itemSelect = new EventEmitter<any>()
  /**
   * table
   * @param {Object}
   */
  @ViewChild('tables') table: any
  /**
   * Table rows
   * @type {Array}
   */
  rows: Array<any> = []
  /**
   * Row selected
   * @type {Array}
   */
  selected: Array<any> = []
  /**
   * @param ColumnMode
   */
  ColumnMode = ColumnMode
  /**
   * @param SelectionType
   */
  SelectionType = SelectionType
  /**
   * @type {{}}
   */
  expanded: any = {}
  /**
   * @type {{}}
   */
  timeout: any
  /**
   * Languages
   * @type {Array<string>}
   */
  langs: string[] = []
  /**
   * If have contract
   * @type {Boolean}
   */
  haveContract: boolean = false
  /**
   * If is proposal
   * @type {Boolean}
   */
  isProposal: boolean = false
  /**
   * If is inspection
   * @type {Boolean}
   */
  isInspection: boolean = false
  /**
   * this is some tools
   * @param router router
   * @param translate translate tool
   * @param engineService service
   */
  constructor(
    private router: Router,
    public translate: TranslateService,
    private engineService: EngineService
  ) {}
  /**
   * @type {{id:number, workOrder:number}}
   */
  public proposalId = {
    id: '',
    workOrder: '',
  }
  /**
   * @type {{id:number, workOrderId:number}}
   */
  public inspectionId = {
    id: '',
    workOrderId: '',
  }
  /**
   * init
   */
  ngOnInit() {
    this.rows = this.listRows
    if (this.isProp == true) {
      this.isProposal = this.isProp
    } else {
      this.isProposal = false
    }
    if (this.isInsp == true) {
      this.isInspection = this.isInsp
    } else {
      this.isInspection = false
    }
    if (this.haveCont == true) {
      this.haveContract = this.haveCont
    } else {
      this.haveContract = false
    }
  }
  /**
   *
   * @param changes simplechanges
   */
  ngOnChanges(changes: SimpleChanges) {
    this.listRows = changes.listRows.currentValue
    this.rows = this.listRows
    this.selected = []
  }
  /**
   * Change language
   * @param event select language
   */
  changeLanguage(event) {
    this.translate.use(event.detail.value)
  }
  /**
   * Data selected
   * @param param0 data selected
   */
  onSelect({ selected }) {
    this.selected.splice(0, this.selected.length)
    this.selected.push(...selected)
    this.itemSelect.emit(this.selected)
  }
  /**
   *
   * @param event
   */
  onActivate(event) {
  }
  add() {
    /**
     * Add new items
     * @property {Array}
     */
    this.selected.push(this.rows[1], this.rows[3])
  }

  update() {
    /**
     * update data selected
     * @property {Array}
     */
    this.selected = [this.rows[1], this.rows[3]]
  }

  remove() {
    /**
     * Deleted selected items
     * @property {Array}
     */
    this.selected = []
  }
  /**
   * Style rows
   * @param row
   * @returns
   */
  displayCheck(row: { name: string }) {
    return row.name !== 'Ethel Price'
  }
  /**
   * Pagination
   * @param event
   */
  onPage(event: any) {
    clearTimeout(this.timeout)
    this.timeout = setTimeout(() => {
    }, 100)
  }
  /**
   * fill rows
   * @param row
   */
  toggleExpanRow(row: any) {
    this.table.rowDetail.toggleExpandRow(row)
  }
  /**
   * Toggle detail
   * @param event
   */
  onDetailToggle(event: any) {
  }
  /**
   * filter
   * @param event
   */
  updateFilter(event: { target: { value: string } }) {
    const val = event.target.value.toLowerCase()
    const temp = this.listRows.filter(function (d) {
      return d.nametoLowerCase().indexOf(val) !== -1 || !val
    })
    this.rows = temp
  }
  /**
   * Redirects the page to the report form
   * @param row
   */
  fillReport(row: { id: string }) {
    this.inspectionId.workOrderId = row.id
    this.engineService.postInspections(this.inspectionId).subscribe((r) => {
      this.inspectionId.id = r.id
      this.router.navigate(['work-orders/inspections/fillReport/', this.inspectionId.id])
    })
  }
  /**
   * Redirects the page to the proposal form
   * @param row
   */
  fillProposal(row: { id: string }) {
    this.proposalId.workOrder = row.id
    this.engineService.postProposal(this.proposalId).subscribe((r) => {
      this.proposalId.id = r.id
      this.router.navigate(['work-orders/proposals/fillProposal', this.proposalId.id])
    })
  }
}

<div>
  <div style="text-align: end;">
    <ion-item class="input-search">
      <ion-label position="stacked">Search:</ion-label>
      <ion-input placeholder="Type to filter the name column..." (keyup)="updateFilter($event)" ></ion-input>
    </ion-item>
  </div>
  

  
  <div style="float:left;width:95%">
    
   <ngx-datatable
      style="width: 95%"
      class="bootstrap"
      [rows]="rows"
      [columnMode]="ColumnMode.force"
      [headerHeight]="'auto'"
      [footerHeight]="'auto'"
      [rowHeight]="'auto'"
      [limit]="5"
      [selected]="selected"
      [selectionType]="SelectionType.checkbox"
      [selectAllRowsOnPage]="false"
      [displayCheck]="displayCheck"
        [scrollbarH]="true"
      (activate)="onActivate($event)"
      (select)="onSelect($event)"
    >
      <ngx-datatable-column
      style="margin: 5px;"
        [width]="30"
        [sortable]="false"
        [canAutoResize]="false"
        [draggable]="true"
        [resizeable]="false"
        [headerCheckboxable]="true"
        [checkboxable]="true"
      >
      </ngx-datatable-column>
      <ngx-datatable-column *ngFor="let column of columns" [name]='column' ></ngx-datatable-column>


      <ngx-datatable-column *ngIf="haveContract===true" name="{{'CONTRACT SIGNED'|translate}}">
        <ng-template let-value="value" let-row="row"  ngx-datatable-cell-template > {{value===true ?"Yes":"No"}} </ng-template>
      </ngx-datatable-column>
      <ngx-datatable-column *ngIf="isInspection===true"name="{{'ACTIONS'|translate}}">
        <ng-template  let-value="value" let-row="row"  ngx-datatable-cell-template>
          <span class="fake-link" id="fake-link-1" (click)="fillReport(row)">{{'FILL REPORT'|translate}}</span>
        </ng-template>
      </ngx-datatable-column>
      <ngx-datatable-column *ngIf="isProposal===true" name="{{'ACTIONS'|translate}}">
        <ng-template let-value="value" let-row="row"  ngx-datatable-cell-template>
          <span class="fake-link" id="fake-link-1"  (click)="fillProposal(row)">{{'FILL PROPOSAL'|translate}}</span>
        </ng-template>
      </ngx-datatable-column>
    </ngx-datatable>
  </div> 
  <!-- <div class="selected-column">
    <h4>
      Selections <small>({{ selected?.length }})</small>
    </h4>
    <ul>
      <li *ngFor="let sel of selected">
        {{ sel.name }}
      </li>
      <li *ngIf="!selected?.length">No Selections</li>
    </ul>
  </div> -->
</div>
